---
- name: Identify and remove bogus NTP servers on Cisco devices
  hosts: ios
  gather_facts: no
  connection: network_cli
  vars:
    authorized_ntp_servers:
      - "192.168.1.1"
      - "192.168.1.2"  # Add all trusted NTP servers here

  tasks:
    - name: Gather configured NTP servers
      cisco.ios.ios_command:
        commands:
          - show run | include ^ntp server
      register: ntp_output

    - name: Extract NTP server IPs from output
      set_fact:
        configured_ntp_servers: "{{ ntp_output.stdout[0].splitlines() | map('regex_search', 'ntp server (\\S+)', '\\1') | select('string') | list }}"

    - name: Identify unauthorized NTP servers
      set_fact:
        bogus_ntp_servers: "{{ configured_ntp_servers | difference(authorized_ntp_servers) }}"

    - name: Remove bogus NTP servers
      when: bogus_ntp_servers | length > 0
      cisco.ios.ios_config:
        lines: "{{ bogus_ntp_servers | map('regex_replace', '^(.*)$', 'no ntp server \\1') | list }}"
      vars:
        ansible_check_mode: false  # Make sure changes are applied

