---
- name: Identify and fix ntp server
  hosts: ios
  gather_facts: no
  connection: network_cli
  vars:
    authorized_ntp_servers:
      - "172.25.254.254"
  tasks:
  - name: Gathered configured NTP servers
    cisco.ios.ios_command:
      commands:
        - show run | include ^ntp server
    register: ntp_output
  - name: Display the output
    ansible.builtin.debug:
      var: ntp_output

  - name: Create the file on controel node 
    ansible.builtin.lineinfile:
      line: "{{ ntp_output.stdout[0] }}"
      path: "./{{ inventory_hostname }}.txt"
      state: present
      create: yes

  - name: Create a backup file 
    ansible.builtin.copy:
      src: "./{{ inventory_hostname }}.txt"
      dest: "./{{ inventory_hostname }}.bkp.txt"
  
  - name: Extract ips from the file 
    set_fact:
      myips: "{{ lookup('file', '{{ inventory_hostname }}.txt') | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"

  - name: Unauthorized ntp server
    set_fact:
      fake_ntp: "{{ myips | difference(authorized_ntp_servers) }}"
  
  - name: Remove bogus ntp servers
    when: fake_ntp | length > 0
    cisco.ios.ios_config:
      lines: "{{ fake_ntp | map('regex_replace', '^(.*)$', 'no ntp server \\1') | list }}"
...
