---
- name: Configure motd banner
  hosts: texas,newyork
  become: true
  tasks:
  - name: Configure Cisco motd banner
    when: ansible_network_os == 'cisco.ios.ios'
    cisco.ios.ios_banner:
      banner: motd
      text: Managed by EX457 Ansible
      state: present
    notify: ios_save_changes
  - name: Configure EOS motd banner
    when: ansible_network_os == 'arista.eos.eos'
    arista.eos.eos_banner:
      banner: motd
      text: Managed by EX457 Ansible
      state: present
  handlers:
    - name: ios_save_changes
      cisco.ios.ios_config:
        save_when: always
...
